### ISSUE TITLE
Save Product Message Box

### ISSUE THREAD

**Issue by SeanIsAtWork** [ancaipen/Provia#12]
Currently when you save a product a box pops up in the bottom right hand corner of the screen telling you whats been saved, the same thing happens if you remove an item by clicking it a second time. We need the message box to disappear after a designated amount of time. 
![image](https://user-images.githubusercontent.com/95431522/145109633-530832a0-3936-4522-be30-f38cd3a18922.png)

**Comment by ancaipen** [comment]
@SeanIsAtWork 

I took a quick look at this looks like some code related to TI wish list.  I can continue to look into this, but it could cause issues with upgrades, etc with this plugin.  I suggest you reach out to the developer at TI wish list about this issue.  Feel free to cc me on the email.  Since you have the premium plugin now you should be able to create support tickets there.  Thanks!

Aaron

**Comment by SeanIsAtWork** [comment]
@ancaipen 

Will do, thanks Aaron.

**Comment by ancaipen** [comment]
FYI: I'm closing this on our end for now.  If there is anything we need to do on our end I can open it again.
