### ISSUE TITLE
Design Center Top of Page

### ISSUE THREAD

**Issue by SeanIsAtWork** [ancaipen/Provia#14]
The design center has a heading and a url that I guess is applied by the preferred dealer widget stuck at the top of the page
![image](https://user-images.githubusercontent.com/95431522/145598059-91f14a25-21ec-46b4-aaa7-c32034c5fddd.png)

**Comment by ancaipen** [comment]
@SeanIsAtWork 

Hi Sean, it looks like you are in design mode.  I copy/pasted the css you had from your original layout and added some additional class names to the divs so it would make it easier to style.  This short code doesn't have any styling applied yet so that will need to done for proper positioning on the page, etc.  The css file you can use is located in this folder: /wp-content/plugins/provia-wheretobuy/css/preferred-dealer.css.  Also, all this content is contained in the div with the class: "perferred-dealer-container". 

![image](https://user-images.githubusercontent.com/43222107/145602554-b84e30fb-595b-4cf1-87c3-09c58064c342.png)

Let me know if this is something you are ok adding the styles here or if you want us to start the process as an example that you can work from just let me know!  

Thanks,

Aaron

**Comment by SeanIsAtWork** [comment]
Oh I see. I actually do think it would be a good idea if you guys were to start the process of styling that. Thanks Aaron.

**Comment by ancaipen** [comment]
This has been fixed by Natalee applying styles.  This issue is closed
