### ISSUE TITLE
Certain sizes are still not resizing on Vision Boards 

### ISSUE THREAD

**Issue by jenkline** [ancaipen/Provia#334]
![Door not resizing capture](https://user-images.githubusercontent.com/104006203/164004286-4a2f36ec-68f2-464e-a481-8cfb44f3f8be.JPG)

**Comment by ancaipen** [comment]
@jenkline - I have adjusted the image sizes so that they are 15% width for horizontal images and 25% width for portrait images.  I added code to pick the images sizes dynamically and below is an example of what I now see when I drag the image above to the canvas for the 1st time.  Let me know if this better.  

![image](https://user-images.githubusercontent.com/43222107/165621046-af022baf-0efb-4c03-9683-405aab0ec4c9.png)

**Comment by jenkline** [comment]
@ancaipen Yes, this is working much better for me now. Thank you!
