### ISSUE TITLE
Save sometimes gets "stuck" when saving vision boards, which results in blank boards being saved

### ISSUE THREAD

**Issue by jenkline** [ancaipen/Provia#335]
![image](https://user-images.githubusercontent.com/104006203/164005671-f75e8029-16c1-415f-ac72-0516236ea3b2.png)
![image](https://user-images.githubusercontent.com/104006203/164005729-096283a2-b348-4a26-bd99-d6547e118f87.png)
![image](https://user-images.githubusercontent.com/104006203/164005803-f4bb9ddd-d3a4-4120-b29c-177c2317db3e.png)

Saving a vision board with just 1-2 images seems to save fine. A full vision board will keep spinning and saying "saving," getting stuck in that mode until finally I just have to exit the page.

**Comment by ancaipen** [comment]
@jenkline  - As an update, I found the issue here, there was a bug.  The project id was not saving correctly when there were too many images which has been fixed.  Take a look and retest when you get a chance.  You can see I created a couple of new vision boards under your account that have a lot of images (see below).

![image](https://user-images.githubusercontent.com/43222107/164464547-fd4d4fa3-35d0-48f5-80e2-201576d72f53.png)
