### ISSUE TITLE
Check entryLink login - my test account doesn't work

### ISSUE THREAD

**Issue by PilotFish3447** [ancaipen/Provia#345]
Can someone check whether the entryLink login works with a real account?  I tested with an old test account Joe Klink gave me that I use on the old site, but it doesn't work on the new site.

**Comment by ancaipen** [comment]
Hi Everyone,

I took a look at this today and I noticed that the credentials that Brian sent me are what I had used previously (see below).  After testing, I found the issue.  This was actually a good test case because I think we could have run into this issue if a user changed their password in EntryLink and not on the website.  

Here is what happened:  We already had this user registered in the system from my previous tests but I must have changed the password in WordPress during my testing because it was not "service1".  To work around this, I added some code so that once an entry link login has been validated as correct, we automatically update the WordPress user's password (if one exists) to be the same password used in EntryLink.

Go ahead and try this again and let me know if it is working as expected.  If everything is working, go ahead and close this issue.  Thanks!      

Credentials Used for Testing:

https://provia.proviaserver-v2.com/entry-link-login/

u: demo
p: service1

![image](https://user-images.githubusercontent.com/43222107/164780918-9aa2c853-e343-4960-949e-a4fc7416969d.png)

After login, I'm now redirected back to the homepage because both EntryLink and Wordpress logins are successful.  Here is the newly updated user in the WordPress admin:

![image](https://user-images.githubusercontent.com/43222107/164781194-1b5bfe61-95f0-4323-bab0-2bcc62613ac5.png)

**Comment by ancaipen** [comment]
@PilotFish3447 - Can this issue be retested to make sure we can close this item?

**Comment by PilotFish3447** [comment]
@ancaipen @plaugs  The login provided above seems to work.  I don't have another entryLink login to test this.  Do we need to try with a different login?

**Comment by PilotFish3447** [comment]
Need to continue testing with a couple additional live accounts.

**Comment by PilotFish3447** [comment]
@plaugs - Can you get a couple other live accounts we can use to confirm this works?

**Comment by plaugs** [comment]
I sent an email to Brian Miller from Brent's team to provide some 'dummy' accounts

**Comment by plaugs** [comment]
Ok here are the dummy accounts:

usernames:
Marketing Test 1
Marketing Test 2
Marketing Test 3
Marketing Test 4

pass for all:
Provia1

**Comment by PilotFish3447** [comment]
@ancaipen @plaugs - I tested the above log-ins - none of them work on the new site.  To verify they're active logins, I used them on the old site and was able to log into entryLink on the old site.

**Comment by PilotFish3447** [comment]
This is fixed.  I'm closing it out.
