### ISSUE TITLE
Grout Visualizer - Saving multiple grout colors per stone color in Design Center 

### ISSUE THREAD

**Issue by PilotFish3447** [ancaipen/Provia#367]
When I click on the heart for images in the grout visualizer, the images don't seem to save into the Design Center.  There's no pop-up asking me to which folder I want to save them in when I click the heart.
![image](https://user-images.githubusercontent.com/78490468/165591506-ea897801-64f2-46bb-9b97-cb3f785d59ae.png)

**Comment by ancaipen** [comment]
@PilotFish3447 - This issue has been fixed.  There was a problem with authenticated users adding items to the grout selector.  I originally had this code in its own php file, but I needed to create it and embed it as a page in wordpress.  Once I did this the item saved to the default wishlist as expected.  Since this is custom coded, I just add the item to the default wishlist.

Here is the new page used in the iframe pop-up: https://provia.proviaserver-v2.com/provia-grout-selector-iframe/?product_id=33224 

![image](https://user-images.githubusercontent.com/43222107/166154696-8839d31a-d65e-4a85-98ad-cab9adaeb3aa.png)

 With that said, I was hesitant originally because this means that this code will now inherit the css from the site which is causing issues with the display.  I did a once over to get this looking ok, but we will need Sean to take a look at the css and update it to stretch and fit the iframe better.  Note that my screenshot below is for an admin so that top black bar won't show up for normal users.
 
![image](https://user-images.githubusercontent.com/43222107/166154809-a8b98dfb-fd42-4afc-b675-7d472395bb61.png)

**Comment by ancaipen** [comment]
@PilotFish3447 @SeanIsAtWork - Nevermind about the additional css work.  Natalee corrected for this and it looks better.  

![image](https://user-images.githubusercontent.com/43222107/166159204-ada38c9a-9e1f-4492-a059-af5a1bd21c0d.png)

**Comment by PilotFish3447** [comment]
@ancaipen - Not sure this is a bug, might be a needed enhancement. The images are saving into Design Center now, but I noticed that you can only like one grout color per image.  You can't add 2 different grout colors of the same stone color to the Design Center.

**Comment by ancaipen** [comment]
@PilotFish3447 : This has been updated.  We are now capturing variations of products in the grout selector.  You may need to clear your cache to see this change.  Here is an example:

The default selected color of white is shown as added to a wishlist upon load:

![image](https://user-images.githubusercontent.com/43222107/167848739-94e5683c-b61f-4f14-9eef-bfbc29c571c3.png)

I can see that this color is showing up in the vision boards (I also had to make adjustments for variations here too):

![image](https://user-images.githubusercontent.com/43222107/167852816-76708c79-76ee-42d7-b599-e7fadf72c0f3.png)

Lastly, if I click and add another color you can see that the color that is not selected, it will reset the heart image.

![image](https://user-images.githubusercontent.com/43222107/167848505-e874085a-37df-4a34-9d6b-2d6fcc645889.png)

**Comment by PilotFish3447** [comment]
Works well. Closing it out.
