### ISSUE TITLE
"Why Choose ProVia" menu hover

### ISSUE THREAD

**Issue by plaugs** [ancaipen/Provia#405]
Mouseover points to the right, all the others do not.
![hover-menu](https://user-images.githubusercontent.com/831625/167447508-876d4d8c-2cb5-4004-82ff-ec9bedd192ba.JPG)

**Comment by SeanIsAtWork** [comment]
@plaugs Why Choose ProVia is a page, Resources and For the Pros arent pages

**Comment by SeanIsAtWork** [comment]
The mouseover arrow pointing to the right. Its intended to suggest to users in a subtle way that this link will take you forward to the why choose provia page. Its a small detail but the importance of directing users to this page is on the lower end since it really only exists as a landing page for the pages in the dropdown: company values, employment, experience and energy efficiency. 

Brian Miller entered a submission that hovering on the resources and for the pros items dont change the cursor to a pointer, so i changed it and had to differentiate the why choose provia menu item in some way.
