### ISSUE TITLE
WTB - Siding distributors option not available 

### ISSUE THREAD

**Issue by PilotFish3447** [ancaipen/Provia#409]
On the WTB page, when I select Siding, it's only letting me see Contractors/Installers - it won't let me select the Distributors button.  On the current website, it let's me select either Contractors/Installers or Distributors to view.
![image](https://user-images.githubusercontent.com/78490468/167932250-050b1e38-37a1-4e29-a8a7-358da2ad2f03.png)
Here's how it looks on current site - I can click either radio button:
![image](https://user-images.githubusercontent.com/78490468/167932399-66cc291c-082e-4a5e-8b41-72e9bd6502c9.png)

**Comment by ancaipen** [comment]
@SeanIsAtWork : It looks like this is a css issue hiding the radio buttons.  I'm guessing your css is applying the changes to all inputs?  Can you update your styles to exclude type = radio?  Thanks!

![image](https://user-images.githubusercontent.com/43222107/168067820-2f208552-5c3a-487a-a77f-11ddb9d440c1.png)

**Comment by SeanIsAtWork** [comment]
@ancaipen Hey Aaron, could you add the respective **for** attributes to those radio button labels? Clicking the label to select an option works on the checkboxes because of this, I inspected the markup and it worked for me so I think thats what the issue is here
![image](https://user-images.githubusercontent.com/95431522/168076649-22ebd5b3-601b-49e4-b873-41227295a2a8.png)

**Comment by ancaipen** [comment]
@SeanIsAtWork  Perfect, I added this and it fixed the issue.  Thanks!  @PilotFish3447 - Let me know if this issue can now be closed?

![image](https://user-images.githubusercontent.com/43222107/168090521-e22eff12-cb4f-4792-b146-b325e0514dc5.png)

**Comment by PilotFish3447** [comment]
@SeanIsAtWork @ancaipen Looks good.  I'm closing it out.
